<?php


namespace app\api\controller;


use app\common\controller\Api;

class Base extends Api
{

    public $noNeedLogin = ['*'];

    public $noNeedRight = ['*'];


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }
}